---
# file: tasks/03-configure_openssh.yml

- name: "03.2 - template openssh server config"
  template:
    src: openssh.server.conf.j2
    dest: "{{ __openssh_config_file_server }}"
    backup: yes
    owner: "0"
    group: "0"
    mode: "0600"
    validate: "{{ __openssh_binary_file_server }} -T -f %s"
  become: True
  notify:
    - restart-openssh-server

- meta: flush_handlers
